version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=time_sheet
      - POSTGRES_PASSWORD=time_sheet
      - POSTGRES_DB=time_sheet
    networks:
      - backend
    ports:
      - "5432:5432"
  db_test:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=time_sheet
      - POSTGRES_PASSWORD=time_sheet
      - POSTGRES_DB=time_sheet
    networks:
      - backend
    ports:
      - "5433:5432"

networks:
  backend:
